In [2]:
import pandas as pd

In [1]:
spd= pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\speed_not0.xlsx')
spd_ratio= pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\speed_ratio.xlsx')

incident=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\incident.xlsx')

TTI_1=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\link_char.xlsx',sheet_name='travel time index')
TTI_2=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\link_char.xlsx',sheet_name='travel time index_2')
#travel time index_1: 최고속도(95%)기준 통과시간-현재속도 기준 통과시간(speed_not0 파일 기준으로 계산)
#travel time index_2: 최고속도(95%)/현재속도(speed_not0 파일 기준으로 계산)

#green_volume_ratio=pd.read...
#green=
#queue_ratio=
#queue=

weather=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\weather.xlsx')
link_char=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\link_char.xlsx')

vol_total=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume.xlsx',sheet_name='total')
vol_thr=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume.xlsx',sheet_name='thr')
vol_left=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume.xlsx',sheet_name='left')
vol_right=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume.xlsx',sheet_name='right')
vol_uturn=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume.xlsx',sheet_name='uturn')
vol_veh=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume.xlsx',sheet_name='veh')
vol_bus_s=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume.xlsx',sheet_name='bus_s')
vol_bus_b=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume.xlsx',sheet_name='bus_b')
vol_truck_s=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume.xlsx',sheet_name='truck_s')
vol_truck_b=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume.xlsx',sheet_name='truck_b')
vol_motor=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume.xlsx',sheet_name='motor')


NameError: name 'pd' is not defined

In [ ]:
# volume에서 교통량을 lane으로 나눠줘볼까..? 차로당평균값으로 나오도록 
# 데이터 사전 결측처리 해주고 정규화 필요
# 신호 db 정리되면 pca 분석해서 변수 축소 필요

new avn         40221         40222         40223         40224  \
0    length_sum  6.857490e+02  4.623511e+02  2.779227e+02  5.883508e+02   
1          lane  3.000000e+00  2.000000e+00  2.000000e+00  3.000000e+00   
2  link_id_near  2.333521e+09  2.333522e+09  2.333522e+09  2.333520e+09   
3   link_id_mid  2.333519e+09  0.000000e+00  0.000000e+00  2.333520e+09   
4   link_id_far  2.333519e+09  0.000000e+00  0.000000e+00  0.000000e+00   
5     spd limit  6.000000e+01  6.000000e+01  6.000000e+01  6.000000e+01   
6   length_near  1.733833e+02  4.623511e+02  2.779227e+02  3.917079e+02   
7    length_mid  2.574386e+02  0.000000e+00  0.000000e+00  1.966429e+02   
8    length_far  2.549272e+02  0.000000e+00  0.000000e+00  0.000000e+00   
9   max spd(95)  5.425000e+01  4.550000e+01  2.025000e+01  6.425000e+01   

          40231         40232         40233         40234         40241  ...  \
0  5.659957e+02  8.834384e+02  5.787701e+02  7.002195e+02  4.746648e+02  ...   
1  3.000000e+00  3.000000e+00  3.000000e+00  3.000000e+00  3.000000e+00  ...   
2  2.333856e+09  2.333518e+09  2.333855e+09  2.333519e+09  2.333520e+09  ...   
3  2.333858e+09  2.333518e+09  2.333854e+09  2.333519e+09  0.000000e+00  ...   
4  0.000000e+00  0.000000e+00  2.333518e+09  2.333521e+09  0.000000e+00  ...   
5  6.000000e+01  6.000000e+01  6.000000e+01  6.000000e+01  6.000000e+01  ...   
6  2.872130e+02  3.184130e+02  1.344817e+02  2.613472e+02  4.746648e+02  ...   
7  2.787827e+02  5.650254e+02  1.741432e+02  2.615814e+02  0.000000e+00  ...   
8  0.000000e+00  0.000000e+00  2.701452e+02  1.772910e+02  0.000000e+00  ...   
9  6.000000e+01  2.875000e+01  7.800000e+01  2.725000e+01  4.225000e+01  ...   

          40373         40374         40381         40382         40383  \
0  4.959885e+02  3.609215e+02  1.560866e+02  3.596415e+02  5.870911e+02   
1  2.000000e+00  3.000000e+00  2.000000e+00  3.000000e+00  2.000000e+00   
2  2.333517e+09  2.333518e+09  2.333812e+09  2.333518e+09  2.333853e+09   
3  2.333517e+09  2.333518e+09  2.333812e+09  2.333518e+09  0.000000e+00   
4  2.333517e+09  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
5  5.000000e+01  6.000000e+01  4.000000e+01  6.000000e+01  3.000000e+01   
6  6.524510e+01  1.705818e+02  5.630035e+01  1.891715e+02  5.870911e+02   
7  1.683063e+02  1.903396e+02  9.978629e+01  1.704700e+02  0.000000e+00   
8  2.624371e+02  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
9  1.375000e+01  4.700000e+01  1.175000e+01  1.950000e+01  1.300000e+01   

          40384         40391         40392         40393         40394  
0  6.975327e+02  6.100166e+02  4.144055e+02  5.577561e+02  8.763076e+02  
1  3.000000e+00  2.000000e+00  3.000000e+00  2.000000e+00  3.000000e+00  
2  2.333518e+09  2.333517e+09  2.333516e+09  2.333517e+09  2.333518e+09  
3  2.333518e+09  2.333850e+09  0.000000e+00  2.333517e+09  2.333518e+09  
4  2.333855e+09  2.333847e+09  0.000000e+00  0.000000e+00  0.000000e+00  
5  6.000000e+01  5.000000e+01  6.000000e+01  3.000000e+01  6.000000e+01  
6  2.527495e+02  1.967898e+02  4.144055e+02  3.418536e+02  5.657722e+02  
7  2.705976e+02  2.530777e+02  0.000000e+00  2.159025e+02  3.105354e+02  
8  1.741857e+02  1.601491e+02  0.000000e+00  0.000000e+00  0.000000e+00  
9  4.175000e+01  1.125000e+01  2.900000e+01  1.275000e+01  4.400000e+01  

[10 rows x 45 columns]

In [5]:
columns=spd.columns

In [6]:
columns

Index(['time',  40221,  40222,  40223,  40224,  40231,  40232,  40233,  40234,
        40241,  40242,  40243,  40244,  40311,  40312,  40313,  40314,  40321,
        40322,  40323,  40324,  40331,  40332,  40333,  40334,  40341,  40342,
        40343,  40344,  40351,  40352,  40353,  40354,  40371,  40372,  40373,
        40374,  40381,  40382,  40383,  40384,  40391,  40392,  40393,  40394],
      dtype='object')

In [7]:
import networkx as nx

G=nx.Graph() #상-하 링크 상호간 영향을 주기 때문에 방향성 없는 그래프로 만듦

In [8]:
for link in columns:
    G.add_node(link)
#노드가 검지기가 됨

In [9]:
for link in columns:
    G.add_edge(link,link)
    
#self loop를 갖도록 함

In [10]:
axis1=[40353,40343,40333,40323,40313]
axis2=[40351,40341,40331,40321,40311]

axis3=[40352,40372,40382,40233,40243]
axis4=[40354,40374,40384,40231,40241]

axis5=[40222,40244,40314]
axis6=[40312,40242,40224]

axis7=[40332,40391,40371]
axis8=[40373,40393,40334]

axis9=[40223,40234,40394,40344]
axis10=[40392,40232,40221]

In [11]:
axes = [axis1, axis2, axis3, axis4, axis5, axis6, axis7, axis8, axis9, axis10]

In [12]:
for axis in axes:
    for j in range(len(axis)):
        try:
            G.add_edge(axis[j],axis[j+1], weight=1/(link_char[axis[j+1]].iloc[0]))
            print(axis[j],axis[j+1])           #인접한 검지기만 엣지로 연결
            print(link_char[axis[j+1]].iloc[0]) # 1/링크 거리를 인접행렬의 가중치로(1차 시도.. 향후 edge랑 가중치 다양하게 구성해보기) 
            
        except IndexError:
            break
            

40353 40343
505.554114247263
40343 40333
366.994239981224
40333 40323
503.06999302009496
40323 40313
280.720207209614
40351 40341
366.88872706025
40341 40331
502.80329036098294
40331 40321
280.80950734899204
40321 40311
452.981479985863
40352 40372
413.12215520928
40372 40382
359.64154135804
40382 40233
578.7700773932829
40233 40243
565.494308665743
40354 40374
360.921489117235
40374 40384
697.532688614321
40384 40231
565.9957165589
40231 40241
474.664842996139
40222 40244
580.544892492954
40244 40314
1701.7183757707
40312 40242
1707.295237286133
40242 40224
588.350807551668
40332 40391
610.016636617877
40391 40371
559.856498109622
40373 40393
557.756093103493
40393 40334
593.982125660618
40223 40234
700.2195223457759
40234 40394
876.30761976857
40394 40344
414.548982027993
40392 40232
883.438435032223
40232 40221
685.749039713941


In [13]:
adj_matrix=nx.adjacency_matrix(G)

#에러 발생 시 scipy1.8.0, networkx 2.8로 버전 맞추고 커널 껐다가 다시 키면 됨

C:\Users\ajou\AppData\Local\Temp\ipykernel_12372\4138473497.py:1: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  adj_matrix=nx.adjacency_matrix(G)


In [14]:
print(adj_matrix.toarray())

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [18]:
G.nodes[40353]['feature1']=15

In [19]:
print(G.nodes[40353]['feature1'])

15


In [15]:
# 시계열 그래프 데이터 생성
# (노드, 엣지, 시간대 정보 등)

In [ ]:
# 그래프 초기화
time_series_graphs = []

for t in range(time_steps):
    G = nx.Graph()
    G.add_nodes_from(nodes)
    
    # 엣지 추가 (임의로 생성)
    for node1 in nodes:
        for node2 in nodes:
            if node1 != node2 and np.random.rand() < 0.2:  # 랜덤한 확률로 엣지 생성
                G.add_edge(node1, node2)
                
    time_series_graphs.append(G)

# 시계열 그래프 데이터 확인
for t, G in enumerate(time_series_graphs):
    print(f"Time step {t+1}: Nodes: {G.nodes()}, Edges: {G.edges()}")

In [ ]:
import dgl
import torch
import torch.nn as nn
import dgl.function as fn
from dgl.nn.pytorch import GATConv, TransformerEncoder, TransformerDecoder

# 시계열 그래프 데이터 생성
# (노드, 엣지, 시간대 정보 등)

# GAT 모델 정의
class GATModel(nn.Module):
    def __init__(self, in_feats, hidden_feats, num_heads, num_layers):
        super(GATModel, self).__init__()
        self.convs = nn.ModuleList()
        self.convs.append(GATConv(in_feats, hidden_feats, num_heads))
        for _ in range(1, num_layers):
            self.convs.append(GATConv(hidden_feats * num_heads, hidden_feats, num_heads))
        
    def forward(self, g, x):
        for conv in self.convs:
            x = conv(g, x).flatten(1)
        return x

# Transformer 모델 정의
class TransformerTimeSeries(nn.Module):
    def __init__(self, input_size, d_model, nhead, num_encoder_layers, num_decoder_layers):
        super(TransformerTimeSeries, self).__init__()
        self.encoder = TransformerEncoder(
            d_model=d_model,
            nhead=nhead,
            num_layers=num_encoder_layers
        )
        self.decoder = TransformerDecoder(
            d_model=d_model,
            nhead=nhead,
            num_layers=num_decoder_layers
        )
        
    def forward(self, src, tgt):
        # src: 시계열 임베딩, tgt: 이전 시점의 예측값
        memory = self.encoder(src)
        output = self.decoder(tgt, memory)
        return output

# GAT 모델 학습 및 임베딩 생성
gat_model = GATModel(input_size, hidden_size, num_heads, num_layers)
gat_emb = gat_model(graph, node_features)

# Transformer 모델 학습 및 예측
transformer_model = TransformerTimeSeries(input_size, d_model, nhead, num_encoder_layers, num_decoder_layers)
predicted_values = transformer_model(gat_emb, previous_predictions)