In [1]:
import pandas as pd

In [2]:
#https://jalynne-kim.medium.com/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%82%AC%EC%9D%B4%EC%96%B8%EC%8A%A4-%EC%A3%BC%EC%84%B1%EB%B6%84-%EB%B6%84%EC%84%9D-pca-principal-component-analysis-%EA%B3%BC-biplot-%EA%B0%9C%EB%85%90%EA%B3%BC-%EC%82%AC%EB%A1%80-%EB%A0%88%EB%93%9C%EC%99%80%EC%9D%B8-%EB%8D%B0%EC%9D%B4%ED%84%B0-437283592031
#pda 분석 주성분 해석방법

In [3]:
spd= pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\speed_not0.xlsx')
spd_ratio= pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\speed_ratio.xlsx')

incident=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\incident_new.xlsx')

TTI_1=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\link_char.xlsx',sheet_name='travel time index')
TTI_2=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\link_char.xlsx',sheet_name='travel time index_2')
#travel time index_1: 최고속도(95%)기준 통과시간-현재속도 기준 통과시간(speed_not0 파일 기준으로 계산)
#travel time index_2: 최고속도(95%)/현재속도(speed_not0 파일 기준으로 계산)

#green_volume_ratio=pd.read...
#green=
#queue_ratio=
#queue=

weather=pd.read_csv('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\weather_hwasung.csv')
link_char=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\link_char.xlsx')

vol_total=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume_not0.xlsx',sheet_name='vol_total')
vol_thr=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume_not0.xlsx',sheet_name='vol_thr')
vol_left=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume_not0.xlsx',sheet_name='vol_left')
vol_right=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume_not0.xlsx',sheet_name='vol_right')
vol_uturn=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume_not0.xlsx',sheet_name='vol_uturn')
vol_veh=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume_not0.xlsx',sheet_name='vol_veh')
vol_bus_s=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume_not0.xlsx',sheet_name='vol_bus_s')
vol_bus_b=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume_not0.xlsx',sheet_name='vol_bus_b')
vol_truck_s=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume_not0.xlsx',sheet_name='vol_truck_s')
vol_truck_b=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume_not0.xlsx',sheet_name='vol_truck_b')
vol_motor=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume_not0.xlsx',sheet_name='vol_motor')
vol_ratio=pd.read_excel('C:\\Users\\ajou\\Desktop\\Data\\dongtan\\volume_not0.xlsx',sheet_name='vol_ratio')
# vol_total에서 교통량을 lane으로 나눠줌
# 40352 공사중인데 교통량 있어서 lane 수 1로 가정


KeyboardInterrupt: 

# 결측치 처리&확인

In [ ]:
#speed는 결측된 시간에서 교통량이 0이라는 것을 확인하여 최고속도(95%)로 대치, 교통량은 빈 셀을 0으로 대치

In [ ]:
spd[spd.isnull().any(axis=1)]

In [ ]:
spd_ratio[spd_ratio.isnull().any(axis=1)]

In [ ]:
incident[incident.isnull().any(axis=1)]

In [ ]:
TTI_1[TTI_1.isnull().any(axis=1)]

In [ ]:
TTI_2[TTI_2.isnull().any(axis=1)]

In [ ]:
weather[weather.isnull().any(axis=1)]

In [ ]:
link_char[link_char.isnull().any(axis=1)]

In [ ]:
vol_total[vol_total.isnull().any(axis=1)]

In [ ]:
vol_thr[vol_thr.isnull().any(axis=1)]

In [ ]:
vol_left[vol_left.isnull().any(axis=1)]

In [ ]:
vol_right[vol_right.isnull().any(axis=1)]

In [ ]:
vol_uturn[vol_uturn.isnull().any(axis=1)]

In [ ]:
vol_veh[vol_veh.isnull().any(axis=1)]

In [ ]:
vol_bus_s[vol_bus_s.isnull().any(axis=1)]

In [ ]:
vol_bus_b[vol_bus_b.isnull().any(axis=1)]

In [ ]:
vol_truck_s[vol_truck_s.isnull().any(axis=1)]

In [ ]:
vol_truck_b[vol_truck_b.isnull().any(axis=1)]

In [ ]:
vol_motor[vol_motor.isnull().any(axis=1)]

In [ ]:
vol_ratio[vol_ratio.isnull().any(axis=1)]

In [ ]:
#incident는 명목형 변수라서 임베딩 과정 필요

In [ ]:
data=[spd, spd_ratio, incident, TTI_1, TTI_2, weather, vol_total, vol_thr, vol_left, vol_right, vol_uturn, vol_veh, vol_bus_s,
      vol_bus_b, vol_truck_s,vol_truck_b,vol_motor,vol_ratio]
#link_char는 뺀다.


In [ ]:
data_name={'spd': spd, 'spd_ratio':spd_ratio,'incident':incident,'TTI_1':TTI_1, 'TTI_2':TTI_2, 'weather':weather, 
      'vol_total':vol_total, 'vol_thr':vol_thr, 'vol_left':vol_left, 'vol_right':vol_right, 'vol_uturn':vol_uturn, 'vol_veh':vol_veh, 
      'vol_bus_s':vol_bus_s,'vol_bus_b':vol_bus_b, 'vol_truck_s':vol_truck_s,'vol_truck_b':vol_truck_b,'vol_motor':vol_motor,'vol_ratio':vol_ratio}
#link_char는 뺀다.


In [ ]:
list(data_name.keys())

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
# 데이터 표준화 - StandardScaler
scalers = {}  # 스케일러를 저장할 딕셔너리

for i, df in enumerate(data):
    scaler = StandardScaler()  # StandardScaler 객체 생성
    df.columns = df.columns.astype(str)
    df.set_index('time', inplace=True)
    scaled_data = scaler.fit_transform(df)  # 데이터 표준화
    scalers[f'scaler_{i}'] = scaler  # 스케일러를 딕셔너리에 저장
    list(data_name.keys())[i]=scaler.fit_transform(df)

    

In [ ]:
#로우 컬럼 수 확인
for df in data:
    print(df.shape)  #날씨 데이터 제외 다 맞음

In [5]:
columns=spd.columns

In [6]:
columns

Index(['time',  40221,  40222,  40223,  40224,  40231,  40232,  40233,  40234,
        40241,  40242,  40243,  40244,  40311,  40312,  40313,  40314,  40321,
        40322,  40323,  40324,  40331,  40332,  40333,  40334,  40341,  40342,
        40343,  40344,  40351,  40352,  40353,  40354,  40371,  40372,  40373,
        40374,  40381,  40382,  40383,  40384,  40391,  40392,  40393,  40394],
      dtype='object')

In [7]:
import networkx as nx

G=nx.Graph() #상-하 링크 상호간 영향을 주기 때문에 방향성 없는 그래프로 만듦

In [8]:
for link in columns:
    G.add_node(link)
#노드가 검지기가 됨

In [9]:
for link in columns:
    G.add_edge(link,link)
    
#self loop를 갖도록 함

In [10]:
axis1=[40353,40343,40333,40323,40313]
axis2=[40351,40341,40331,40321,40311]

axis3=[40352,40372,40382,40233,40243]
axis4=[40354,40374,40384,40231,40241]

axis5=[40222,40244,40314]
axis6=[40312,40242,40224]

axis7=[40332,40391,40371]
axis8=[40373,40393,40334]

axis9=[40223,40234,40394,40344]
axis10=[40392,40232,40221]

In [11]:
axes = [axis1, axis2, axis3, axis4, axis5, axis6, axis7, axis8, axis9, axis10]

In [12]:
for axis in axes:
    for j in range(len(axis)):
        try:
            G.add_edge(axis[j],axis[j+1], weight=1/(link_char[axis[j+1]].iloc[0]))
            print(axis[j],axis[j+1])           #인접한 검지기만 엣지로 연결
            print(link_char[axis[j+1]].iloc[0]) # 1/링크 거리를 인접행렬의 가중치로(1차 시도.. 향후 edge랑 가중치 다양하게 구성해보기) 
            
        except IndexError:
            break
            

40353 40343
505.554114247263
40343 40333
366.994239981224
40333 40323
503.06999302009496
40323 40313
280.720207209614
40351 40341
366.88872706025
40341 40331
502.80329036098294
40331 40321
280.80950734899204
40321 40311
452.981479985863
40352 40372
413.12215520928
40372 40382
359.64154135804
40382 40233
578.7700773932829
40233 40243
565.494308665743
40354 40374
360.921489117235
40374 40384
697.532688614321
40384 40231
565.9957165589
40231 40241
474.664842996139
40222 40244
580.544892492954
40244 40314
1701.7183757707
40312 40242
1707.295237286133
40242 40224
588.350807551668
40332 40391
610.016636617877
40391 40371
559.856498109622
40373 40393
557.756093103493
40393 40334
593.982125660618
40223 40234
700.2195223457759
40234 40394
876.30761976857
40394 40344
414.548982027993
40392 40232
883.438435032223
40232 40221
685.749039713941


In [13]:
adj_matrix=nx.adjacency_matrix(G)

#에러 발생 시 scipy1.8.0, networkx 2.8로 버전 맞추고 커널 껐다가 다시 키면 됨

C:\Users\ajou\AppData\Local\Temp\ipykernel_12372\4138473497.py:1: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  adj_matrix=nx.adjacency_matrix(G)


In [14]:
print(adj_matrix.toarray())

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [18]:
G.nodes[40353]['feature1']=15

In [19]:
print(G.nodes[40353]['feature1'])

15


In [15]:
# 시계열 그래프 데이터 생성
# (노드, 엣지, 시간대 정보 등)

In [ ]:
# 그래프 초기화
time_series_graphs = []

for t in range(time_steps):
    G = nx.Graph()
    G.add_nodes_from(nodes)
    
    # 엣지 추가 (임의로 생성)
    for node1 in nodes:
        for node2 in nodes:
            if node1 != node2 and np.random.rand() < 0.2:  # 랜덤한 확률로 엣지 생성
                G.add_edge(node1, node2)
                
    time_series_graphs.append(G)

# 시계열 그래프 데이터 확인
for t, G in enumerate(time_series_graphs):
    print(f"Time step {t+1}: Nodes: {G.nodes()}, Edges: {G.edges()}")

In [ ]:
import dgl
import torch
import torch.nn as nn
import dgl.function as fn
from dgl.nn.pytorch import GATConv, TransformerEncoder, TransformerDecoder

# 시계열 그래프 데이터 생성
# (노드, 엣지, 시간대 정보 등)

# GAT 모델 정의
class GATModel(nn.Module):
    def __init__(self, in_feats, hidden_feats, num_heads, num_layers):
        super(GATModel, self).__init__()
        self.convs = nn.ModuleList()
        self.convs.append(GATConv(in_feats, hidden_feats, num_heads))
        for _ in range(1, num_layers):
            self.convs.append(GATConv(hidden_feats * num_heads, hidden_feats, num_heads))
        
    def forward(self, g, x):
        for conv in self.convs:
            x = conv(g, x).flatten(1)
        return x

# Transformer 모델 정의
class TransformerTimeSeries(nn.Module):
    def __init__(self, input_size, d_model, nhead, num_encoder_layers, num_decoder_layers):
        super(TransformerTimeSeries, self).__init__()
        self.encoder = TransformerEncoder(
            d_model=d_model,
            nhead=nhead,
            num_layers=num_encoder_layers
        )
        self.decoder = TransformerDecoder(
            d_model=d_model,
            nhead=nhead,
            num_layers=num_decoder_layers
        )
        
    def forward(self, src, tgt):
        # src: 시계열 임베딩, tgt: 이전 시점의 예측값
        memory = self.encoder(src)
        output = self.decoder(tgt, memory)
        return output

# GAT 모델 학습 및 임베딩 생성
gat_model = GATModel(input_size, hidden_size, num_heads, num_layers)
gat_emb = gat_model(graph, node_features)

# Transformer 모델 학습 및 예측
transformer_model = TransformerTimeSeries(input_size, d_model, nhead, num_encoder_layers, num_decoder_layers)
predicted_values = transformer_model(gat_emb, previous_predictions)